### ISSUE TITLE
SafariStand appears to install fine on Safari 11, no favicons anymore though

### ISSUE THREAD

**Issue by dillanmills** [anakinsk/SafariStand#51]
Sidebar is working fine. Stacked tabs in 'show all tabs' not working. favicons not working.

**Comment by ilovesafaristand** [comment]
Mine just stopped working too! What happened?

**Comment by dillanmills** [comment]
Safari updated to v11.

Thanks,
Dillan
________________________________

**Comment by ilovesafaristand** [comment]
I don't see any safari updates.
Safaristand seems installed. I had to reinstall it.
The stand menu is there

No favicons are present :(

**Comment by dillanmills** [comment]
Okay well I don’t know about your issue but mine is specific to the safari 11 update. What is your safari version currently installed?


On September 19, 2017 at 2:55:28 PM, ilovesafaristand (notifications@github.com) wrote:

I don't see any safari updates.
Safaristand seems installed. I had to reinstall it.
The stand menu is there

No favicons are present :(

**Comment by ilovesafaristand** [comment]
Just made the edit, same as you. Safari 11 update killed it.

**Comment by JayBrown** [comment]
Same here. Updated to Safari 11 on El Capitan, but SafariStand is not working.

**Comment by trwrt** [comment]
JayBrown, I was able to get the Stand menu and sidebar tabs back by re-running the SafariStand Patcher, but I do not have any favicons in my tabs any longer just like dillanmills.

**Comment by ilovesafaristand** [comment]
@anakinsk calling the battle horn! Please help!

**Comment by JayBrown** [comment]
@trwrt: I'm still on 10.11.6, so there is no library validation yet, and the patcher won't be needed (Sierra and above only). So the problem seems to be a standard version imcompatibility, as e.g. shown by the missing favicons in other cases. That means we probably need SafariStand 11 for El Capitan, and SafariStand 11 plus patcher for Sierra and above.

**Comment by kinoute** [comment]
Same here, El Capitan 10.11.6, Safari 11 released yesterday, SafariStand doesn't work.

I miss my full address bar :(

**Comment by suessmann** [comment]
Somehow while I was sleeping Safari updated and no I have no favicons... it's nightmare really, the best-perfomance browser w/o such a common thing nowadays. Hope @anakinsk will make it alive asap.

**Comment by riegelstamm** [comment]
I think we all just need to tell Apple we want favicons and whatever else: https://www.apple.com/feedback/

**Comment by kinoute** [comment]
FWIW, on 10.11.6, here is what the console says when launching Safari 11:

> 20/09/2017 21:59:43,000 kernel[0]: AMFI: Safari(pid 5361) - [deny-mmap] mapped executable file has no team identifier in its signature: /Users/kinoute/Library/Application Support/SIMBL/Plugins/SafariStand.bundle/Contents/MacOS/SafariStand

> 20/09/2017 21:59:43,096 Safari[5361]: Error loading /Users/kinoute/Library/Application Support/SIMBL/Plugins/SafariStand.bundle/Contents/MacOS/SafariStand:  dlopen(/Users/kinoute/Library/Application Support/SIMBL/Plugins/SafariStand.bundle/Contents/MacOS/SafariStand, 265): no suitable image found.  Did find:
	/Users/kinoute/Library/Application Support/SIMBL/Plugins/SafariStand.bundle/Contents/MacOS/SafariStand: mmap() error 1 at address=0x10E51E000, size=0x00061000 segment=__TEXT in Segment::map() mapping /Users/kinoute/Library/Application Support/SIMBL/Plugins/SafariStand.bundle/Contents/MacOS/SafariStand

**Comment by dillanmills** [comment]
@kinoute how did you filter console? I am not seeing anything related to safaristand or SIMBL anywhere in console on 10.12.6. Is there a particular log you looked in?

**Comment by kinoute** [comment]
@dillanmills I didn't filter anything, I just looked at the console while launching Safari. Maybe it has to do with my OS X Version which differs from yours.

Apparently Safari 11 on El Capitan brings the Library Validation, therefore we need a patcher just like for Sierra. I tried the actual patcher but it replaces the Safari binary with a version that only works for Sierra+. Therefore, my Safari doesn't start and I got an error in the console saying that this version only works for 10.12+.

If somebody still has Safari 10.1 on El Capitan, we might get it to work by using his Safari binary.

**Comment by anakinsk** [comment]
Hi all, I will take a look this weekend, hopefully its not big and can be fixed relatively quickly.

@kinoute I think in your case the stand failed to load completely, you need to re-apply the patcher.

**Comment by kinoute** [comment]
I managed to make it work on El Capitan! It was tricky because Apple does not let you install an older version of Safari correctly (it doesn't replace all the correct files).

**Only do that if you know what you're doing and backup your Safari application before.**

I just used the same process the patcher uses (which is explained in this long discussion : https://github.com/anakinsk/SafariStand/issues/38). Basically, you just replace a few files in your new Safari app (11) with some old ones from Safari 10.1.

I used these old binary files of Safari 10.1.2 for El Capitan 10.11.6 and copy them into the Safari (11) app Contents Folder. Use "Show Package Contents" on Safari app to see the folder.

Here are the binary files: 
[Safari 10.1.2 OS X 10.11.6 Binary Files.zip](https://github.com/anakinsk/SafariStand/files/1319291/Safari.10.1.2.OS.X.10.11.6.Binary.Files.zip)

Safari will show up as 10.1 in the "About" section but you are still using Safari 11. See my screenshot, you can see the "auto-play blocker" new option on my Safari despite showing "10.1.2".

![capture d ecran 2017-09-20 a 23 17 41](https://user-images.githubusercontent.com/623763/30668554-6cc24e22-9e5b-11e7-9be1-dfa54d73b6d0.png)

**Comment by schulzj01** [comment]
In regards to the patches, Keep in mind that this will change Safari's reported version from 11 to 10.1.  If you run any kind of security scanners on your system such as Tenable's Security Center, it will flag Safari as an older version.  If you are required to patch your systems, you won't have a way of reverting Safari's reported version to 11.0 to get past your scan.

**Comment by ilovesafaristand** [comment]
Anyone else reporting success? I'm waiting for the official patch from anakinsk :)

**Comment by dillanmills** [comment]
The standard patcher does the same thing with reverting the safari version to 10.0.1, so it would get caught in a scanner anyway. The patch by @kinoute is just to get safaristand installed on El Capitan because v11 blocked it the same way Sierra blocked it. I don't know for sure, maybe @kinoute can confirm, but I imagine the favicons and other bugs still don't work on El Capitan with the patch.

**Comment by dillanmills** [comment]
What a stupid place for the 'close issue' button...

**Comment by kinoute** [comment]
Yeah, the actual patcher provided by @anakinsk is only for Sierra because the Safari binary files used in it are from Safari 10.1 Sierra version, which doesn't work on El Capitan. I tried yesterday and after the installation my Safari wouldn't start anymore because it wasn't compatible with El Capitan. So I had to patch it "manually" with my own binary files.

I guess the best way to handle this will be to create a patcher that uses & replaces the correct Safari binary files, depending of the OS X version. Weekend is not far away, I'm pretty sure it's coming soon, no need to get yourself in trouble with my "patch"!

**Comment by jason-hub** [comment]
I just installed on Safari 11 (Sierra 10.12.6). The "Stand" menu appears, but the following settings have no effect:

"Show Icon in Tab Bar"

The icons DO display in the bookmarks sidebar, but the tab bar is much more important.

**Comment by ilovesafaristand** [comment]
Weekend here! Here's hoping for @anakinsk with the gift of the year! GM of High Sierra is out so could be good time to get upgrading if we have some good news :)

**Comment by jason-hub** [comment]
Do it for my 6-year-old daughter!  It's her birthday.  She misses Safari icons because she's learning to read and the icons help her to recognize pages better (especially now that the title bar is gone)!  :)

**Comment by ilovesafaristand** [comment]
Do it for the kids! @anakinsk

**Comment by anakinsk** [comment]
Update: It appears that Safari 11 now uses updated version of Webkit, which got rid of very important (for us, not for them) function that we used to get the favicon image, before actually inserting it manually into the tabbar. The rest of the code appears to be ok, however cause the webkit function now always returns nil theres nothing to insert, therefore we see nothing in the tab bar.

I have absolutely zero knowledge about webkit, all I understand at the moment is that the function we used was deprecated long time ago, and now they finally removed it as a part of a code cleaning process. It is unclear at this stage whether they have a replacement function that I could use or not.

Regardless of whether there's a replacement function in a webkit, I am pretty sure that I can just implement our own favicon downloading and caching system to be completely independent from webkit in the future. But since this is a rather complicated task I will explore the first option and try to find a replacement function in webkit before trying to put any effort into the second option.

There's no ETA at the moment, but I will try to find a solution ASAP, for the kids, their parents, and peace in all over the world :) 

In a meantime I will strongly discourage everyone, who reckons they cannot live without the favicons, from updating to either High Sierra or Safari 11.

**Comment by dillanmills** [comment]
I wonder about (at least temporarily) just using the image that safari uses for pinned tabs? That is native built in, you would just have to fetch it for every tab instead of just the pinned ones. Obviously they are monochrome so it might not be ideal, but at some point safari is fetching an image from the servers so we just need to find that and utilize it.

**Comment by ilovesafaristand** [comment]
Thanks @anakinsk  I hope some webkit folk can contribute to the code here.

**Comment by staniki** [comment]
@anakinsk Вань, а можно будет сделать в эбаут, что бы отображалась актуальная версия сафари? Это уже для перфекционистов :)

**Comment by seika7** [comment]
Does this do what you're looking for?
https://faviconographer.com

**Comment by dillanmills** [comment]
It’s an imperfect solution, this one felt a lot more native.

**Comment by jason-hub** [comment]
Faviconographer.com is not working fully on OS Sierra (12.6.4) and Safari 11.  It only shows icons in the bookmarks bar, not the tabs.

**Comment by anakinsk** [comment]
@staniki к сожалению, нет :-(

@dillanmills I reckon that would be similar to finding a replacement function in a webkit. Google Chrome uses it as well right and it does have favicon so maybe theres something. I just need to find enough spare time to do a proper research.

**Comment by anakinsk** [comment]
@seika7 why are we even discussing 3rd party apps in here :-D
This thread is for safari stand compatibility issue.

**Comment by ilovesafaristand** [comment]
the faviconographer is a poor solution. There is a delay for the tabs appearing, graphics glitches, you close safari and the favicons are overlayed on the desktop. Lots of lag as if the favicons are floating on another layer.

Could any of this code help?

https://github.com/gingerbeardman/favemoji.safariextension

**Comment by trwrt** [comment]
I know there is a more modern standard now where the page specifies it in the headers, but as a first pass can you just grab http://site.com/favicon.ico?  That worked on most of the random sites I tried it on.

**Comment by jason-hub** [comment]
I am having withdrawals!

**Comment by anakinsk** [comment]
Good news. Managed to get favicons back on Safari 11 and Sierra 10.12.6. I will test the solution a bit more, and will also install High Sierra to check if it works there as well. 

Hopefully will be able to roll out a public version soon.

<img width="846" alt="screen shot 2017-10-01 at 4 00 12 pm" src="https://user-images.githubusercontent.com/5235150/31051396-8f9583f4-a6c3-11e7-8aff-245ae5d428bb.png">

**Comment by jason-hub** [comment]
AWESOMENESS! Thank you so much!  Can't wait.

**Comment by jason-hub** [comment]
@anakinsk

Is it ready to release yet?  Please say it's ready.  :)

**Comment by anakinsk** [comment]
Safari 11 support for Sierra is ready. However, Safari 11 support for High Sierra is not.
Even tho one might think that the same versions of Safari are absolutely identical between OS releases, in reality they are not. Whatever you have on Sierra is not really fully functional Safari 11, basically its just Safari 10 with latest webkit and security updates.

High Sierra is a completely different story. This is where you actually get the latest version of everything. They changed their internal framework again and there's some work needed to be done before I can say that Stand is fully functional on that OS.

Are there many people in here who need Sierra support and don't really care about High Sierra?

**Comment by trwrt** [comment]
I'm still on Sierra and would use the new SafariStand if you decide to release it.

**Comment by anakinsk** [comment]
I will definitely support both Sierra and High Sierra. Currently they are scheduled to go into the release together, but just thinking if there are still many ppl on who didn't upgrade the OS but who did upgrade their Safari.. I could split the release into two and push Sierra support say sometime later today so they are not waiting for something they don't actually need. Put a thumb on this comment if you think I should do it so I see how many of you actually need that ;)

**Comment by jason-hub** [comment]
I am still on Sierra.  I always prefer to wait a few months before applying any major OS update.  (I've had some bad experiences in the past.)  So, a standalone update just for Sierra would be great for me.  :)

**Comment by levifig** [comment]
I'm probably going to stick to Sierra until 10.13.1 or maybe even 10.13.2 TBH… So, Safari 11 for Sierra is my main priority (any way to get it working with Safari Technology Preview, officially?). :)

**Comment by anakinsk** [comment]
Implemented in 11.0.

**Comment by anakinsk** [comment]
@levifig there's no plans for Technology Preview support at the moment.

**Comment by ghost** [comment]
Awesome work, it works beautifully! What did you end up doing to get it to work?

**Comment by cooperred** [comment]
So Stand is updated to support Safari 11 in Sierra, but not High Sierra right now?

**Comment by BigMacOS** [comment]
Works fine in High Sierra

**Comment by cooperred** [comment]
Has something changed?

> Safari 11 support for Sierra is ready. However, Safari 11 support for High Sierra is not.

**Comment by anakinsk** [comment]
@cooperred yes you see "Implemented in 11.0." kinda indicates that it has been actually implemented in 11.0 🤔

**Comment by anakinsk** [comment]
@cooperred but I agree that this bug name might be a bit confusing. So to reiterate, SafariStand 11 now works on Sierra and High Sierra but might not work on El Capitan.

**Comment by SchmollTroll** [comment]
I'm on El Capitan and can confirm that it did not even show up in the menu bar. Tried that with original Safari 11 and with applied patch from kinoute :-(
What I really miss are the dated download folders - found no other practicable solution so far...
